src/memorylayout.jl, test/test_layouts.jl
This lets `MemoryLayout` act on an instance instead of its type, which is (I think) what its docstring says should work.
=> MemoryLayout(::AbstractArray)

Project.toml, src/lmul.jl, test/runtests.jl
Fixes Stack overflow from `ArrayLayouts.lmul!(::Number, ::AbstractArray)`
=> Scalar l/rmul! fallbacks

.github/workflows/ci.yml, Project.toml, src/ArrayLayouts.jl, src/diagonal.jl, src/ldiv.jl, src/memorylayout.jl, src/triangular.jl, test/test_layoutarray.jl, test/test_layouts.jl, test/test_muladd.jl
This is to support a more general `*Tridiagonal` in LazyBandedMatrices.jl with types differing.
=> Allow more general *TridiagonalLayout, improve interface

Project.toml, src/diagonal.jl, src/memorylayout.jl
@jagot this would avoid the deprecation warning though I'm inclined to not merge this until the next breaking change tag
=> Support QuasiDiagonal

Project.toml, src/ArrayLayouts.jl, src/muladd.jl, test/test_muladd.jl
This tracks changes in Julia-1.7 and fixes #81
=> Remove usage of buffers (#81)

Project.toml, src/ArrayLayouts.jl, src/mul.jl
=> Restrict `check_mul_axes` to specific Q-matrix-types

src/ArrayLayouts.jl, src/factorizations.jl, src/lmul.jl, src/memorylayout.jl, src/mul.jl, src/muladd.jl, src/triangular.jl
I didn't check, but unbound type parameters often cause performance issues, so this may not be merely cosmetic.
=> remove unbound type parameters

.github/workflows/ci.yml, Project.toml, src/ArrayLayouts.jl, src/cumsum.jl, src/factorizations.jl, src/ldiv.jl, src/lmul.jl, src/memorylayout.jl, src/mul.jl, src/muladd.jl, test/test_layoutarray.jl, test/test_muladd.jl
~~This is a companion PR to https://github.com/JuliaLang/julia/pull/46196, in case that one gets accepted. This will fail on nightly before that LinearAlgebra PR gets merged.~~ I have removed the `AdjointQ` stuff and left the pure code clean-up part. I carefully reviewed which functions are actually overloaded (hence need to be `import`ed)  and which ones are only `use`d. I also removed obsolete package specifiers and added a few factorization `ldiv!`s to make the package proof for some work in `LinearAlgebra.jl`.
=> Code clean-up

Project.toml, README.md, src/diagonal.jl, src/ldiv.jl, test/test_layoutarray.jl
Adjusts tests to the generalizations in https://github.com/JuliaLang/julia/pull/47107, which make the tests pass.
Closes #43 and closes #44 by the way.
=> Turn broken `rdiv` tests to proper tests

src/mul.jl
This method seems to have been missed, and adding this provides a significant performance boost in matrix*vector operations:
```julia
julia> B = brand(4000, 4000, 5, 5);
julia> v = rand(size(B,2));
julia> @btime mul!($(copy(v)), $B, $v, 1.0, 1.0);
40.232 ms (0 allocations: 0 bytes) # master
22.385 μs (0 allocations: 0 bytes) # PR
```
=> 5-arg mul! for matrix*vector

src/muladd.jl
This is a fringe case, and it's only hit for incorrect input types. Nonetheless, it's better to be less cryptic in the error message here.
```julia
julia> A = BandedMatrix(0=>fill(Day(2), 4))
4×4 BandedMatrix{Day} with bandwidths (0, 0):
2 days    ⋅       ⋅       ⋅   
⋅     2 days    ⋅       ⋅   
⋅       ⋅     2 days    ⋅   
⋅       ⋅       ⋅     2 days
julia> B = BandedMatrix(0=>fill(today(), 4), 1=>fill(today(), 3))
4×4 BandedMatrix{Date} with bandwidths (0, 1):
2023-05-02  2023-05-02    ⋅                   ⋅   
⋅                 2023-05-02  2023-05-02    ⋅   
⋅                   ⋅                 2023-05-02  2023-05-02
⋅                   ⋅                   ⋅                 2023-05-02
julia> A * B
ERROR: UndefVarError: `T` not defined
Stacktrace:
[1] …
```
=> Improve error message if scalarone hits bottom type

Project.toml, src/muladd.jl
The order of the loop was cache unfriendly, but it was written this way because the range of the row variable may depend on the column one. However, we may carry out a quick check to ascertain whether the row range is actually independent of the column one, in which case we may switch them and loop in a cache-friendly manner. This branching improves performance in banded*dense matmul. The original behavior is retained in the fallback branch.
```julia
julia> B = brand(4000, 4000, 5, 5);
julia> X = rand(4000, 4000);
julia> @btime $B * $X;
977.570 ms (2 allocations: 122.07 MiB) # master
518.942 ms (2 allocations: 122.07 MiB) # PR
```
=> Improve cache localization in default_blasmul

Project.toml, src/mul.jl
This came up in https://github.com/JuliaLang/julia/pull/43972. Generally speaking, there are (classes of) matrix types that dominates the respective other factor (in terms of whose multiplication code should be applied). One such example is LayoutMatrix, obviously, other examples are LinearAlgebra's AbstractTriangular and "banded" matrices. For the latter, this PR adds the required disambiguating `mul!` methods.
=> Help disambiguation with special matrix types

Project.toml, src/ArrayLayouts.jl
Extending this function avoids ambiguities in the first argument (the `MemoryLayout`), in case one package defines 
```julia
sub_materialize(::Any, V, ax::Tuple{axtypes})
```
and another defines 
```julia
sub_materialize(::SpecificLayout, V, ax)
```
Ideally, this would be done as
```julia
sub_materialize(L, V, ax) = sub_materialize(UnknownLayout(), V, ax)
sub_materialize(::UnknownLayout, V, ax) = Array(V)
```
and the first method above would be rewritten as
```julia
sub_materialize(::UnknownLayout, V, ax::Tuple{axtypes})
```
but this is breaking at present, as that's not how it's defined at present.  Introducing a separate function is a workaround, but this makes the intent clear.
=> Add `sub_materialize_axes` to dispatch on axes

Project.toml, src/ArrayLayouts.jl, src/memorylayout.jl
Late adaptation to https://github.com/JuliaLang/julia/pull/26307.
=> remove usage of 2-arg `LA.AbstractTriangular`

src/ldiv.jl
In a downstream PR I encountered an ambiguity issue caused by ArrayLayouts: https://github.com/JuliaStats/PDMats.jl/actions/runs/5720019750/job/15499152626?pr=175#step:6:201 This PR implements the suggested solution (adding a method for `StridedMatrix`).
=> Fix ambiguity issue with `rdiv!`

src/ArrayLayouts.jl
This is internal to `Base`, and is unnecessary here
=> Don't use `@propagate_inbounds_meta`

Project.toml, src/memorylayout.jl, test/test_layouts.jl
This allows one to define an efficient `BandedMatrix * OneElement`. Currently, I've gone against the trend a bit, and specialized on the array type as well as the memory layout, instead of defining a layout for `OneElement` (I wasn't quite sure if that might introduce ambiguities, but if this is desired, we may do it in another PR).
=> Add colsupport for OneElelement

Project.toml, src/mul.jl
This makes 
```julia
julia> A = brand(4,4,-2,2); w=rand(4);
julia> mul!(ones(size(A,2)), A', w, 1.0, 1.0)
4-element Vector{Float64}:
1.0
1.0
1.3629633338145817
1.2059646417643002
```
avoid generic fallbacks.
=> Add 5-term Matrix-vector mul

src/mul.jl
This avoids calling the internal function `_ind2sub`, and uses a `CartesianIndex` instead.
=> Replace ind2sub by CartesianIndices

test/test_layoutarray.jl, test/test_ldiv.jl, test/test_muladd.jl
Replace `all(A .=== B)` by `A == B` in tests, which should be identical for numeric arrays, but should be faster.
=> Replace elementwise equality by array equality in tests

Project.toml, src/cumsum.jl, test/infinitearrays.jl, test/test_cumsum.jl
This makes an infinite `RangeCumsum` work correctly on the present Julia nightly. In any case, it probably doesn't hurt to have this defined.
=> Specialize axes for rangecumsum

Project.toml, src/mul.jl
This makes operations like
```julia
julia> A = BandedBlockBandedMatrix{Float64}(undef, 1:10,1:10, (1,1), (1,1));
julia> A.data .= randn.();
julia> U = UnitUpperTriangular(A);
julia> b = randn(size(U,1));
julia> U * b
```
use layout-based `mul` methods instead of hitting a default fallback.
=> Add `mul` methods for `AbstractTriangular` of `LayoutMatrix`

Project.toml, src/memorylayout.jl, src/muladd.jl, test/test_layouts.jl
After this,
```julia
julia> O = OneElement(2, (2,3), (3,3))
3×3 OneElement{Int64, 2, Tuple{Int64, Int64}, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}:
⋅  ⋅  ⋅
⋅  ⋅  2
⋅  ⋅  ⋅
julia> rowsupport(O)
3:3
julia> colsupport(O)
2:2
```
Also, a bugfix in `default_blasmul!` which makes the following work with the newly defined supports:
```julia
julia> B = brand(6,6,2,2);
julia> O = OneElement(2, (4,4), size(B));
julia> O * B ≈ Array(O) * B
true
```
=> row/colsupport for OneElementMatrix

Project.toml, src/muladd.jl
The idea is that this flag will help downstream. If `C isa Zeros` (as in `MulAdd(::Mul)`), the destination is explicitly zeroed by calling `_fill_copyto!` in `muladd!`. Storing this information would mean that we would be able to save an additional zero-`fill!` downstream.
The impact:
```julia
julia> B = brand(6000,6000,4000,4000);
julia> O = OneElement(1, 3, size(B,2));
julia> @btime $B * $O;
4.203 μs (2 allocations: 46.92 KiB) # master
3.839 μs (2 allocations: 46.92 KiB) # PR
julia> @btime $B[:, 3]; # the matrix multiplication with a OneElementMatrix is now equally fast as slicing
3.936 μs (4 allocations: 47.00 KiB)
```
=> Store if `C isa Zeros` in a `MulAdd`

.gitignore, Project.toml, test/test_layoutarray.jl, test/test_ldiv.jl
The result of `LAPACK.gesv!` has changed slightly between v1.10 and v1.11, so the exact equality doesn't hold anymore. This result is not guaranteed to be stable across versions, and only an approximate equality is guaranteed to hold.
Also specialize `Base.cconvert` for some of the test array types, as this is used by `pointer` on v1.11.
=> Change exact comparison with LAPACK.gesv to approx

Project.toml, src/ArrayLayouts.jl, src/cumsum.jl, test/test_cumsum.jl
The in-place sort should only be defined for `Base.OneTo` cumsums, as otherwise we can't guarantee an increasing result.
=> Fix sort for RangeCumSum

src/cumsum.jl, test/test_cumsum.jl
After this, the following work correctly:
```julia
julia> r = RangeCumsum(Base.IdentityUnitRange(4:6))
3-element RangeCumsum{Int64, Base.IdentityUnitRange{UnitRange{Int64}}} with indices 4:6:
4
9
15
julia> r = RangeCumsum((-1.0:3.0:5.0)*im)
3-element RangeCumsum{ComplexF64, StepRangeLen{ComplexF64, Base.TwicePrecision{ComplexF64}, Base.TwicePrecision{ComplexF64}, Int64}}:
0.0 - 1.0im
0.0 + 1.0im
0.0 + 6.0im
```
=> Fix indexing for non-Real and offset ranges

.github/workflows/docs.yml
This will reduce potential breakages from changes in the display of types.
=> Run doc job on v1.10

src/cumsum.jl, test/test_cumsum.jl
The sum of a `RangeCumsum` may be evaluated in `O(1)` time:
On master
```julia
julia> r = RangeCumsum(1:10000);
julia> @btime sum($r)
3.781 μs (0 allocations: 0 bytes)
166716670000
```
This PR
```julia
julia> @btime sum($r)
5.876 ns (0 allocations: 0 bytes)
166716670000
```
This also consolidates the indexing methods.
=> Sum for RangeCumsum

src/cumsum.jl, test/test_cumsum.jl
Avoid overflows in indexing a `RangeCumsum` by being careful with factors.
On master
```julia
julia> r = RangeCumsum(typemax(Int) .+ (0:0))
1-element RangeCumsum{Int64, UnitRange{Int64}}:
9223372036854775807
julia> sum(r)
-1
```
This PR
```julia
julia> sum(r)
9223372036854775807
```
=> Avoid overflow in indexing and sum

Project.toml, src/cumsum.jl, test/test_cumsum.jl
This allows us to promote two `RangeCumsum` instances to a common type.
=> `promote_rule` for `RangeCumSum`

Project.toml, src/cumsum.jl, test/test_cumsum.jl
This makes `sort` work for infinite `RangeCumsum`s:
```julia
julia> r = RangeCumsum(-2:∞)
ℵ₀-element RangeCumsum{Int64, InfiniteArrays.InfUnitRange{Int64}} with indices OneToInf():
-2
-3
-3
-2
0
3
7
12
18
⋮
julia> sort(r)
vcat(5-element Vector{Int64}, ℵ₀-element RangeCumsum{Int64, InfiniteArrays.InfUnitRange{Int64}} with indices OneToInf()) with indices OneToInf():
-3
-3
-2
-2
0
3
7
12
18
⋮
```
=> Sort `RangeCumsum` for `AbstractUnitRange`

Project.toml, src/ArrayLayouts.jl, src/memorylayout.jl, test/test_ldiv.jl
Unfortunately, quite a lot of packages seem to be stuck at ArrayLayouts < 1.0 which errors on 1.11 due to the number of parameters change in the triangular array.
This backports the fixes so that this package passes test on 0.18 so that the packages stuff on older version keep working. Normally I wouldn't bother with this but there were enough packages that I felt it made sense.
A maintainer here would have to:
- create a `release-0.18` branch from this commit https://github.com/JuliaLinearAlgebra/ArrayLayouts.jl/commit/449a3e5966691feb67456a7d919620cac911f75b
- merge this PR into that branch
- make a new release from that merge commit
This should release 0.18.19 which should work on 1.11.
=> Backports to fix 0.18 on 1.11

test/test_muladd.jl
This seems somewhat architecture dependent, as I can't reproduce the failure locally.
=> Fix failing QR scaling test on v1.6

src/muladd.jl
Needed for https://github.com/JuliaArrays/LazyArrays.jl/pull/331
Not sure the proper way to add a test for this since the ambiguity isn't actually there until `using BandedMatrices`
=> Add new method to fix possible ambiguity between `similar(::MulAdd{<:DiagonalLayout, <:AbstractBandedLayout})` and friends

Project.toml, src/ArrayLayouts.jl, src/mul.jl, test/infinitearrays.jl, test/test_layoutarray.jl
Need this to support multiplication between infinite matrices, as found in https://github.com/DanielVandH/InfiniteRandomArrays.jl/issues/5.
To make sure the methods are being tested properly, I extended the minimal InfiniteArrays.jl module in the tests to include a (hopefully minimal) definition of an infinite vector and an infinite matrix, and the resulting named matrices to mimic those from InfiniteRandomMatrices.jl. 
`InfVec` and `InfMat` were initially just matrices which returned the indices, e.g. `InfVec()[i] = i`, but I wanted to be sure the methods were properly copying the data and accessing the correct entries, so I convert it into a random vector.
=> Add * for more matrices defined from layouts

Project.toml, src/mul.jl, test/test_layoutarray.jl
We may potentially go either way. In this, I have chosen to return a `FillArray`, as this avoids allocating the destination.
=> Disambiguate FillMatrix * LayoutVector

Project.toml, src/diagonal.jl, test/test_layoutarray.jl
Currently, there are method ambiguities on v1.10, because of which these paths were not being tested. These ambiguities are resolved on the currently nightly, which reveals a stack-overflow in these methods. This arises because an operation like
```julia
(D::Diagonal{<:Any, <:LayoutVector}) * (B::Bidiagonal{<:Any, <:LayoutVector})
```
internally calls
```julia
copy(M::Lmul{<:DiagonalLayout,<:BidiagonalLayout})
```
but this method was calling `D * B` again, leading to a cycle. To avoid this, we now broadcast `D.diag` over the other matrix. The added tests all work on nightly where there are no method ambiguities anymore, and the `Bidiagonal` ones work on current versions as well.
=> Resolve stack-overflow in Diagonal*Bidiagonal and (Sym)Tridiagonal

Project.toml, src/ArrayLayouts.jl
Since v1.10 is the LTS now, we may focus development only on v1.10+. Versions of this pacakge <v1.11 would continue to be compatible with julia v1.6.
=> Set julia compat to v1.10

test/infinitearrays.jl, test/runtests.jl, test/test_cumsum.jl, test/test_layoutarray.jl
This ensures that there are no method overwritten warnings in tests
=> Include infinitearrays only once in tests

Project.toml, src/diagonal.jl, test/test_layoutarray.jl
This works around the missing `convert` methods to `Bidiagonal`/`Tridiagonal`, and fixes the failing tests on nightly
=> Fix banded-diagonal `Lmul`/`Rmul` copy

.github/workflows/ci.yml
It seems this job was being run twice, once in CI and once separately as documentation. This removes the CI job.
=> Remove duplicate documentation job in CI

src/muladd.jl
There's no need to use linear indexing here, since the conversion from Cartesian to linear is cheap.
=> Use indices instead of stride in `default_blasmul`

Project.toml, src/ArrayLayouts.jl, test/test_layouts.jl
Currently, `sub_materialize` (through `sub_materialize_axes`) falls back to materializing on CPU. This PR generalizes that logic by determining the output destination with `similar`, which helps to support non-Array types like GPU arrays. As a stand-in for other GPU arrays, I test this using [JLArrays.JLArray](https://github.com/JuliaGPU/GPUArrays.jl/tree/master/lib/JLArrays), which is a reference implementation for the GPUArrays.jl interface that runs on CPU.
An alternative design would be to define memory layouts for GPU arrays (i.e. #9), which would allow more customizability for GPU array backends, however I think it is helpful to have fallbacks that "just work" if reasonable parts of the Base AbstractArray interface are implemented.
I hit this issue because I was testing out …
=> Fix `sub_materialize` for GPU arrays
